Just starting
NatLibFi/melinda-marc-record-merge-reducers-js pull request #3
Opened 2020-10-13 16:19 UTC by ssilvonen

Starting out, everything is still a mess. I don't understand how to use the existing code (https://www.npmjs.com/package/@natlibfi/marc-record-merge) together with this.

2020-10-19 07:21 UTC, natlibfi-arlehiko requested changes
I just updated the Jira issue but I'll summary it here too:
- This package's index.js exports all of it's own reducers and also a list of these reducers which can be fed to marc-record-merge to use all of Melinda's generic reducers.

The contents of index.js would look like this:
```js
import * as reducers from './reducers';
export * from './reducers';
export default reducers;
```

(This exports each reducer with their own name separately also, if some application wants only use certain reducers from the package).

Example of implementing a reducer: 010 (Specified [here](https://workgroups.helsinki.fi/x/3JwzCQ)):

`"010": { "action": "copy", "options": { "compareWithout": ["9"] } },`

This would otherwise work with copy reducer from `marc-record-merge` but subfield 9 needs to be excluded from comparison. Excluding subfields is non-Melinda specific feature which would be good to have in the copy reducer in marc-record-merge. This package (marc-marc-record-merge-reducers) would then export the copy reducer with parameters for field 010 with subfield 9 excluded from comparison.

2020-12-04 07:39 UTC, natlibfi-jonollil commented on src/reducers/field006.spec.js
> +  const {expect} = chai;
https://github.com/NatLibFi/melinda-commons-js/blob/ac0868f904c8f247046ff70128056bf40c25a6b0/src/subRecordPicker.spec.js#L29

2020-12-04 07:43 UTC, natlibfi-jonollil requested changes

2020-12-04 07:43 UTC, natlibfi-jonollil commented on src/reducers/field006.spec.js
> +      const tagPattern = new RegExp(getFixture({components: ['tagPattern.txt'], reader: READERS.TEXT}), 'u');
Since tag pattern stays as same for whole test and is one liner, it can be hard coded.

2020-12-04 07:47 UTC, natlibfi-jonollil commented on src/reducers/melindaCustomMergeFunctions.js
> +// Custom functions for Melinda merge
File could be named as something more common, like 'utils.js' and there you could collect all functions what can be used in any reducer later on. (checkDropSubfields and/or compareSubValues)

2023-01-22 19:30 UTC, merged